language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin
  - rm -rf /home/travis/.cargo/bin/wasm-pack
  - rm -rf target/debug/incremental/{async_executors,build_script_build}-*
  - rm -rf target/debug/.fingerprint/async_executors-*
  - rm -rf target/debug/build/async_executors-*
  - rm -rf target/debug/deps/libasync_executors-*
  - rm -rf target/debug/deps/async_executors-*
  - rm -rf target/debug/{async_executors,libasync_executors}.d
  - cargo clean -p async_executors

install:
#  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      script:
        - bash ci/test.bash
        # - bash ci/wasm.bash
        - bash ci/deny.bash


    - name: linux nightly rust
      os  : linux
      dist: bionic # required for tarpaulin binary distribution to work.
      rust: nightly

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin
            # - libgtk-3-dev # needed for headless (sic) firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1372998
            # - libdbus-glib-1-dev # firefox

      script:
        - bash ci/test.bash
        # - bash ci/wasm.bash
        - bash ci/coverage.bash


    - name: osx stable rust
      os  : osx
      rust: stable

      addons:
        firefox: latest

      script:
        - bash ci/test.bash
        # - bash ci/wasm.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      # for wasm tests
      #
      # addons:
      #   firefox: latest

      script:
        - bash ci/test.bash
        # - bash ci/wasm.bash # can't find firefox binary, I'm giving up.





